repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
        files: \.(js|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-yaml
        files: \.(yaml|yml)$
    -   id: check-merge-conflict
        files: \.(js|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-symlinks
-   repo: https://github.com/willthames/ansible-lint.git
    rev: v3.4.23
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
        args:
        - --exclude=.travis.yml
        - --exclude=ansible/requirements.yml
        - --exclude=ansible/galaxy_roles
        - --exclude=test
